export const ReminderActionTypes = {
  FETCH_REMINDERS_START: "FETCH_REMINDERS_START",
  FETCH_REMINDERS_SUCCESS: "FETCH_REMINDERS_SUCCESS",
  FETCH_REMINDERS_FAILURE: "FETCH_REMINDERS_FAILURE",
  ADD_REMINDERS: "ADD_REMINDERS",
  DELETE_REMINDERS: "DELETE_REMINDERS"
};
